DROP DATABASE IF EXISTS mvc;
CREATE DATABASE IF NOT EXISTS mvc;
USE mvc;

DROP TABLE IF EXISTS user;
CREATE TABLE IF NOT EXISTS user(
    id INT AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    hash VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    isAdmin TINYINT(4) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);