DROP DATABASE IF EXISTS mvc;
CREATE DATABASE IF NOT EXISTS mvc;
USE mvc;

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users(
    users_id INT AUTO_INCREMENT,
    username TEXT NOT NULL,
    password TEXT NOT NULL,
    email TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (users_id)
);